// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PP3.Models;

namespace PP3.Migrations
{
    [DbContext(typeof(PatentDbContext))]
    [Migration("20191013060234_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PP3.Models.Patent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Autors");

                    b.Property<string>("CPC");

                    b.Property<string>("Country");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PublicationDate");

                    b.HasKey("ID");

                    b.ToTable("Patents");
                });
#pragma warning restore 612, 618
        }
    }
}
